package com.nf147.dao;

import com.nf147.entity.Connect;
import java.util.List;

public interface ConnectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String connectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated
     */
    int insert(Connect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated
     */
    Connect selectByPrimaryKey(String connectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated
     */
    List<Connect> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Connect record);
}