package com.nf147.dao;

import com.nf147.entity.Scope;
import java.util.List;

public interface ScopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String scopeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scope
     *
     * @mbg.generated
     */
    int insert(Scope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scope
     *
     * @mbg.generated
     */
    Scope selectByPrimaryKey(String scopeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scope
     *
     * @mbg.generated
     */
    List<Scope> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Scope record);
}