package com.nf147.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminID
     *
     * @mbg.generated
     */
    private String adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminName
     *
     * @mbg.generated
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminSex
     *
     * @mbg.generated
     */
    private Integer adminsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.UserID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminType
     *
     * @mbg.generated
     */
    private Integer admintype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminChina
     *
     * @mbg.generated
     */
    private String adminchina;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminSite
     *
     * @mbg.generated
     */
    private String adminsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminPwd
     *
     * @mbg.generated
     */
    private String adminpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminTEL
     *
     * @mbg.generated
     */
    private String admintel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminNotes
     *
     * @mbg.generated
     */
    private String adminnotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminID
     *
     * @return the value of admin.AdminID
     *
     * @mbg.generated
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminID
     *
     * @param adminid the value for admin.AdminID
     *
     * @mbg.generated
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminName
     *
     * @return the value of admin.AdminName
     *
     * @mbg.generated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminName
     *
     * @param adminname the value for admin.AdminName
     *
     * @mbg.generated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminSex
     *
     * @return the value of admin.AdminSex
     *
     * @mbg.generated
     */
    public Integer getAdminsex() {
        return adminsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminSex
     *
     * @param adminsex the value for admin.AdminSex
     *
     * @mbg.generated
     */
    public void setAdminsex(Integer adminsex) {
        this.adminsex = adminsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.UserID
     *
     * @return the value of admin.UserID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.UserID
     *
     * @param userid the value for admin.UserID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminType
     *
     * @return the value of admin.AdminType
     *
     * @mbg.generated
     */
    public Integer getAdmintype() {
        return admintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminType
     *
     * @param admintype the value for admin.AdminType
     *
     * @mbg.generated
     */
    public void setAdmintype(Integer admintype) {
        this.admintype = admintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminChina
     *
     * @return the value of admin.AdminChina
     *
     * @mbg.generated
     */
    public String getAdminchina() {
        return adminchina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminChina
     *
     * @param adminchina the value for admin.AdminChina
     *
     * @mbg.generated
     */
    public void setAdminchina(String adminchina) {
        this.adminchina = adminchina == null ? null : adminchina.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminSite
     *
     * @return the value of admin.AdminSite
     *
     * @mbg.generated
     */
    public String getAdminsite() {
        return adminsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminSite
     *
     * @param adminsite the value for admin.AdminSite
     *
     * @mbg.generated
     */
    public void setAdminsite(String adminsite) {
        this.adminsite = adminsite == null ? null : adminsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminPwd
     *
     * @return the value of admin.AdminPwd
     *
     * @mbg.generated
     */
    public String getAdminpwd() {
        return adminpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminPwd
     *
     * @param adminpwd the value for admin.AdminPwd
     *
     * @mbg.generated
     */
    public void setAdminpwd(String adminpwd) {
        this.adminpwd = adminpwd == null ? null : adminpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminTEL
     *
     * @return the value of admin.AdminTEL
     *
     * @mbg.generated
     */
    public String getAdmintel() {
        return admintel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminTEL
     *
     * @param admintel the value for admin.AdminTEL
     *
     * @mbg.generated
     */
    public void setAdmintel(String admintel) {
        this.admintel = admintel == null ? null : admintel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminNotes
     *
     * @return the value of admin.AdminNotes
     *
     * @mbg.generated
     */
    public String getAdminnotes() {
        return adminnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminNotes
     *
     * @param adminnotes the value for admin.AdminNotes
     *
     * @mbg.generated
     */
    public void setAdminnotes(String adminnotes) {
        this.adminnotes = adminnotes == null ? null : adminnotes.trim();
    }
}