package com.nf147.entity;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.AreaID
     *
     * @mbg.generated
     */
    private String areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.AreaName
     *
     * @mbg.generated
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.CityID
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.AreaID
     *
     * @return the value of area.AreaID
     *
     * @mbg.generated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.AreaID
     *
     * @param areaid the value for area.AreaID
     *
     * @mbg.generated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.AreaName
     *
     * @return the value of area.AreaName
     *
     * @mbg.generated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.AreaName
     *
     * @param areaname the value for area.AreaName
     *
     * @mbg.generated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.CityID
     *
     * @return the value of area.CityID
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.CityID
     *
     * @param cityid the value for area.CityID
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }
}