package com.nf147.entity;

import java.util.Date;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ClientID
     *
     * @mbg.generated
     */
    private String clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ClientName
     *
     * @mbg.generated
     */
    private String clientname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ClientSex
     *
     * @mbg.generated
     */
    private Integer clientsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.UserID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ClientPwd
     *
     * @mbg.generated
     */
    private String clientpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ClientTEL
     *
     * @mbg.generated
     */
    private String clienttel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ClientDate
     *
     * @mbg.generated
     */
    private Date clientdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ClientSite
     *
     * @mbg.generated
     */
    private String clientsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ClientNotes
     *
     * @mbg.generated
     */
    private String clientnotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ClientID
     *
     * @return the value of client.ClientID
     *
     * @mbg.generated
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ClientID
     *
     * @param clientid the value for client.ClientID
     *
     * @mbg.generated
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ClientName
     *
     * @return the value of client.ClientName
     *
     * @mbg.generated
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ClientName
     *
     * @param clientname the value for client.ClientName
     *
     * @mbg.generated
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ClientSex
     *
     * @return the value of client.ClientSex
     *
     * @mbg.generated
     */
    public Integer getClientsex() {
        return clientsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ClientSex
     *
     * @param clientsex the value for client.ClientSex
     *
     * @mbg.generated
     */
    public void setClientsex(Integer clientsex) {
        this.clientsex = clientsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.UserID
     *
     * @return the value of client.UserID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.UserID
     *
     * @param userid the value for client.UserID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ClientPwd
     *
     * @return the value of client.ClientPwd
     *
     * @mbg.generated
     */
    public String getClientpwd() {
        return clientpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ClientPwd
     *
     * @param clientpwd the value for client.ClientPwd
     *
     * @mbg.generated
     */
    public void setClientpwd(String clientpwd) {
        this.clientpwd = clientpwd == null ? null : clientpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ClientTEL
     *
     * @return the value of client.ClientTEL
     *
     * @mbg.generated
     */
    public String getClienttel() {
        return clienttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ClientTEL
     *
     * @param clienttel the value for client.ClientTEL
     *
     * @mbg.generated
     */
    public void setClienttel(String clienttel) {
        this.clienttel = clienttel == null ? null : clienttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ClientDate
     *
     * @return the value of client.ClientDate
     *
     * @mbg.generated
     */
    public Date getClientdate() {
        return clientdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ClientDate
     *
     * @param clientdate the value for client.ClientDate
     *
     * @mbg.generated
     */
    public void setClientdate(Date clientdate) {
        this.clientdate = clientdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ClientSite
     *
     * @return the value of client.ClientSite
     *
     * @mbg.generated
     */
    public String getClientsite() {
        return clientsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ClientSite
     *
     * @param clientsite the value for client.ClientSite
     *
     * @mbg.generated
     */
    public void setClientsite(String clientsite) {
        this.clientsite = clientsite == null ? null : clientsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ClientNotes
     *
     * @return the value of client.ClientNotes
     *
     * @mbg.generated
     */
    public String getClientnotes() {
        return clientnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ClientNotes
     *
     * @param clientnotes the value for client.ClientNotes
     *
     * @mbg.generated
     */
    public void setClientnotes(String clientnotes) {
        this.clientnotes = clientnotes == null ? null : clientnotes.trim();
    }
}