package com.nf147.entity;

import java.util.Date;

public class Connect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.ConnectID
     *
     * @mbg.generated
     */
    private String connectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.ConnectStart
     *
     * @mbg.generated
     */
    private String connectstart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.ConnectMiddle
     *
     * @mbg.generated
     */
    private String connectmiddle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.ConnectTerminus
     *
     * @mbg.generated
     */
    private String connectterminus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.ConnectType
     *
     * @mbg.generated
     */
    private Integer connecttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.ConnectDate
     *
     * @mbg.generated
     */
    private Date connectdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.ConnectNotes
     *
     * @mbg.generated
     */
    private String connectnotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.ConnectID
     *
     * @return the value of connect.ConnectID
     *
     * @mbg.generated
     */
    public String getConnectid() {
        return connectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.ConnectID
     *
     * @param connectid the value for connect.ConnectID
     *
     * @mbg.generated
     */
    public void setConnectid(String connectid) {
        this.connectid = connectid == null ? null : connectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.ConnectStart
     *
     * @return the value of connect.ConnectStart
     *
     * @mbg.generated
     */
    public String getConnectstart() {
        return connectstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.ConnectStart
     *
     * @param connectstart the value for connect.ConnectStart
     *
     * @mbg.generated
     */
    public void setConnectstart(String connectstart) {
        this.connectstart = connectstart == null ? null : connectstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.ConnectMiddle
     *
     * @return the value of connect.ConnectMiddle
     *
     * @mbg.generated
     */
    public String getConnectmiddle() {
        return connectmiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.ConnectMiddle
     *
     * @param connectmiddle the value for connect.ConnectMiddle
     *
     * @mbg.generated
     */
    public void setConnectmiddle(String connectmiddle) {
        this.connectmiddle = connectmiddle == null ? null : connectmiddle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.ConnectTerminus
     *
     * @return the value of connect.ConnectTerminus
     *
     * @mbg.generated
     */
    public String getConnectterminus() {
        return connectterminus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.ConnectTerminus
     *
     * @param connectterminus the value for connect.ConnectTerminus
     *
     * @mbg.generated
     */
    public void setConnectterminus(String connectterminus) {
        this.connectterminus = connectterminus == null ? null : connectterminus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.ConnectType
     *
     * @return the value of connect.ConnectType
     *
     * @mbg.generated
     */
    public Integer getConnecttype() {
        return connecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.ConnectType
     *
     * @param connecttype the value for connect.ConnectType
     *
     * @mbg.generated
     */
    public void setConnecttype(Integer connecttype) {
        this.connecttype = connecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.ConnectDate
     *
     * @return the value of connect.ConnectDate
     *
     * @mbg.generated
     */
    public Date getConnectdate() {
        return connectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.ConnectDate
     *
     * @param connectdate the value for connect.ConnectDate
     *
     * @mbg.generated
     */
    public void setConnectdate(Date connectdate) {
        this.connectdate = connectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.ConnectNotes
     *
     * @return the value of connect.ConnectNotes
     *
     * @mbg.generated
     */
    public String getConnectnotes() {
        return connectnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.ConnectNotes
     *
     * @param connectnotes the value for connect.ConnectNotes
     *
     * @mbg.generated
     */
    public void setConnectnotes(String connectnotes) {
        this.connectnotes = connectnotes == null ? null : connectnotes.trim();
    }
}