package com.nf147.entity;

import java.util.Date;

public class Lorry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lorry.LorryID
     *
     * @mbg.generated
     */
    private String lorryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lorry.LorryModel
     *
     * @mbg.generated
     */
    private String lorrymodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lorry.LorryCO
     *
     * @mbg.generated
     */
    private String lorryco;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lorry.PathID
     *
     * @mbg.generated
     */
    private String pathid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lorry.LorryYield
     *
     * @mbg.generated
     */
    private Date lorryyield;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lorry.LorryBuy
     *
     * @mbg.generated
     */
    private Date lorrybuy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lorry.yieldNotes
     *
     * @mbg.generated
     */
    private String yieldnotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lorry.LorryID
     *
     * @return the value of lorry.LorryID
     *
     * @mbg.generated
     */
    public String getLorryid() {
        return lorryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lorry.LorryID
     *
     * @param lorryid the value for lorry.LorryID
     *
     * @mbg.generated
     */
    public void setLorryid(String lorryid) {
        this.lorryid = lorryid == null ? null : lorryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lorry.LorryModel
     *
     * @return the value of lorry.LorryModel
     *
     * @mbg.generated
     */
    public String getLorrymodel() {
        return lorrymodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lorry.LorryModel
     *
     * @param lorrymodel the value for lorry.LorryModel
     *
     * @mbg.generated
     */
    public void setLorrymodel(String lorrymodel) {
        this.lorrymodel = lorrymodel == null ? null : lorrymodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lorry.LorryCO
     *
     * @return the value of lorry.LorryCO
     *
     * @mbg.generated
     */
    public String getLorryco() {
        return lorryco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lorry.LorryCO
     *
     * @param lorryco the value for lorry.LorryCO
     *
     * @mbg.generated
     */
    public void setLorryco(String lorryco) {
        this.lorryco = lorryco == null ? null : lorryco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lorry.PathID
     *
     * @return the value of lorry.PathID
     *
     * @mbg.generated
     */
    public String getPathid() {
        return pathid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lorry.PathID
     *
     * @param pathid the value for lorry.PathID
     *
     * @mbg.generated
     */
    public void setPathid(String pathid) {
        this.pathid = pathid == null ? null : pathid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lorry.LorryYield
     *
     * @return the value of lorry.LorryYield
     *
     * @mbg.generated
     */
    public Date getLorryyield() {
        return lorryyield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lorry.LorryYield
     *
     * @param lorryyield the value for lorry.LorryYield
     *
     * @mbg.generated
     */
    public void setLorryyield(Date lorryyield) {
        this.lorryyield = lorryyield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lorry.LorryBuy
     *
     * @return the value of lorry.LorryBuy
     *
     * @mbg.generated
     */
    public Date getLorrybuy() {
        return lorrybuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lorry.LorryBuy
     *
     * @param lorrybuy the value for lorry.LorryBuy
     *
     * @mbg.generated
     */
    public void setLorrybuy(Date lorrybuy) {
        this.lorrybuy = lorrybuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lorry.yieldNotes
     *
     * @return the value of lorry.yieldNotes
     *
     * @mbg.generated
     */
    public String getYieldnotes() {
        return yieldnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lorry.yieldNotes
     *
     * @param yieldnotes the value for lorry.yieldNotes
     *
     * @mbg.generated
     */
    public void setYieldnotes(String yieldnotes) {
        this.yieldnotes = yieldnotes == null ? null : yieldnotes.trim();
    }
}