package com.nf147.entity;

public class OrderList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderID
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderType
     *
     * @mbg.generated
     */
    private Integer ordertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderNumber
     *
     * @mbg.generated
     */
    private String ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderName
     *
     * @mbg.generated
     */
    private String ordername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderKG
     *
     * @mbg.generated
     */
    private Integer orderkg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderMail
     *
     * @mbg.generated
     */
    private String ordermail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderMailSite
     *
     * @mbg.generated
     */
    private String ordermailsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderProfile
     *
     * @mbg.generated
     */
    private String orderprofile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderStatus
     *
     * @mbg.generated
     */
    private Integer orderstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderPostPhone
     *
     * @mbg.generated
     */
    private String orderpostphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderCNEE
     *
     * @mbg.generated
     */
    private String ordercnee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderPhone
     *
     * @mbg.generated
     */
    private String orderphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderStart
     *
     * @mbg.generated
     */
    private String orderstart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderMiddle
     *
     * @mbg.generated
     */
    private String ordermiddle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderTerminus
     *
     * @mbg.generated
     */
    private String orderterminus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderShip
     *
     * @mbg.generated
     */
    private Long ordership;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderDC
     *
     * @mbg.generated
     */
    private Long orderdc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderMove
     *
     * @mbg.generated
     */
    private Long ordermove;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderSum
     *
     * @mbg.generated
     */
    private String ordersum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderCar
     *
     * @mbg.generated
     */
    private String ordercar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.OrderNotes
     *
     * @mbg.generated
     */
    private String ordernotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderID
     *
     * @return the value of order_list.OrderID
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderID
     *
     * @param orderid the value for order_list.OrderID
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderType
     *
     * @return the value of order_list.OrderType
     *
     * @mbg.generated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderType
     *
     * @param ordertype the value for order_list.OrderType
     *
     * @mbg.generated
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderNumber
     *
     * @return the value of order_list.OrderNumber
     *
     * @mbg.generated
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderNumber
     *
     * @param ordernumber the value for order_list.OrderNumber
     *
     * @mbg.generated
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderName
     *
     * @return the value of order_list.OrderName
     *
     * @mbg.generated
     */
    public String getOrdername() {
        return ordername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderName
     *
     * @param ordername the value for order_list.OrderName
     *
     * @mbg.generated
     */
    public void setOrdername(String ordername) {
        this.ordername = ordername == null ? null : ordername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderKG
     *
     * @return the value of order_list.OrderKG
     *
     * @mbg.generated
     */
    public Integer getOrderkg() {
        return orderkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderKG
     *
     * @param orderkg the value for order_list.OrderKG
     *
     * @mbg.generated
     */
    public void setOrderkg(Integer orderkg) {
        this.orderkg = orderkg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderMail
     *
     * @return the value of order_list.OrderMail
     *
     * @mbg.generated
     */
    public String getOrdermail() {
        return ordermail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderMail
     *
     * @param ordermail the value for order_list.OrderMail
     *
     * @mbg.generated
     */
    public void setOrdermail(String ordermail) {
        this.ordermail = ordermail == null ? null : ordermail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderMailSite
     *
     * @return the value of order_list.OrderMailSite
     *
     * @mbg.generated
     */
    public String getOrdermailsite() {
        return ordermailsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderMailSite
     *
     * @param ordermailsite the value for order_list.OrderMailSite
     *
     * @mbg.generated
     */
    public void setOrdermailsite(String ordermailsite) {
        this.ordermailsite = ordermailsite == null ? null : ordermailsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderProfile
     *
     * @return the value of order_list.OrderProfile
     *
     * @mbg.generated
     */
    public String getOrderprofile() {
        return orderprofile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderProfile
     *
     * @param orderprofile the value for order_list.OrderProfile
     *
     * @mbg.generated
     */
    public void setOrderprofile(String orderprofile) {
        this.orderprofile = orderprofile == null ? null : orderprofile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderStatus
     *
     * @return the value of order_list.OrderStatus
     *
     * @mbg.generated
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderStatus
     *
     * @param orderstatus the value for order_list.OrderStatus
     *
     * @mbg.generated
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderPostPhone
     *
     * @return the value of order_list.OrderPostPhone
     *
     * @mbg.generated
     */
    public String getOrderpostphone() {
        return orderpostphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderPostPhone
     *
     * @param orderpostphone the value for order_list.OrderPostPhone
     *
     * @mbg.generated
     */
    public void setOrderpostphone(String orderpostphone) {
        this.orderpostphone = orderpostphone == null ? null : orderpostphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderCNEE
     *
     * @return the value of order_list.OrderCNEE
     *
     * @mbg.generated
     */
    public String getOrdercnee() {
        return ordercnee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderCNEE
     *
     * @param ordercnee the value for order_list.OrderCNEE
     *
     * @mbg.generated
     */
    public void setOrdercnee(String ordercnee) {
        this.ordercnee = ordercnee == null ? null : ordercnee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderPhone
     *
     * @return the value of order_list.OrderPhone
     *
     * @mbg.generated
     */
    public String getOrderphone() {
        return orderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderPhone
     *
     * @param orderphone the value for order_list.OrderPhone
     *
     * @mbg.generated
     */
    public void setOrderphone(String orderphone) {
        this.orderphone = orderphone == null ? null : orderphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderStart
     *
     * @return the value of order_list.OrderStart
     *
     * @mbg.generated
     */
    public String getOrderstart() {
        return orderstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderStart
     *
     * @param orderstart the value for order_list.OrderStart
     *
     * @mbg.generated
     */
    public void setOrderstart(String orderstart) {
        this.orderstart = orderstart == null ? null : orderstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderMiddle
     *
     * @return the value of order_list.OrderMiddle
     *
     * @mbg.generated
     */
    public String getOrdermiddle() {
        return ordermiddle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderMiddle
     *
     * @param ordermiddle the value for order_list.OrderMiddle
     *
     * @mbg.generated
     */
    public void setOrdermiddle(String ordermiddle) {
        this.ordermiddle = ordermiddle == null ? null : ordermiddle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderTerminus
     *
     * @return the value of order_list.OrderTerminus
     *
     * @mbg.generated
     */
    public String getOrderterminus() {
        return orderterminus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderTerminus
     *
     * @param orderterminus the value for order_list.OrderTerminus
     *
     * @mbg.generated
     */
    public void setOrderterminus(String orderterminus) {
        this.orderterminus = orderterminus == null ? null : orderterminus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderShip
     *
     * @return the value of order_list.OrderShip
     *
     * @mbg.generated
     */
    public Long getOrdership() {
        return ordership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderShip
     *
     * @param ordership the value for order_list.OrderShip
     *
     * @mbg.generated
     */
    public void setOrdership(Long ordership) {
        this.ordership = ordership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderDC
     *
     * @return the value of order_list.OrderDC
     *
     * @mbg.generated
     */
    public Long getOrderdc() {
        return orderdc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderDC
     *
     * @param orderdc the value for order_list.OrderDC
     *
     * @mbg.generated
     */
    public void setOrderdc(Long orderdc) {
        this.orderdc = orderdc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderMove
     *
     * @return the value of order_list.OrderMove
     *
     * @mbg.generated
     */
    public Long getOrdermove() {
        return ordermove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderMove
     *
     * @param ordermove the value for order_list.OrderMove
     *
     * @mbg.generated
     */
    public void setOrdermove(Long ordermove) {
        this.ordermove = ordermove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderSum
     *
     * @return the value of order_list.OrderSum
     *
     * @mbg.generated
     */
    public String getOrdersum() {
        return ordersum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderSum
     *
     * @param ordersum the value for order_list.OrderSum
     *
     * @mbg.generated
     */
    public void setOrdersum(String ordersum) {
        this.ordersum = ordersum == null ? null : ordersum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderCar
     *
     * @return the value of order_list.OrderCar
     *
     * @mbg.generated
     */
    public String getOrdercar() {
        return ordercar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderCar
     *
     * @param ordercar the value for order_list.OrderCar
     *
     * @mbg.generated
     */
    public void setOrdercar(String ordercar) {
        this.ordercar = ordercar == null ? null : ordercar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.OrderNotes
     *
     * @return the value of order_list.OrderNotes
     *
     * @mbg.generated
     */
    public String getOrdernotes() {
        return ordernotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.OrderNotes
     *
     * @param ordernotes the value for order_list.OrderNotes
     *
     * @mbg.generated
     */
    public void setOrdernotes(String ordernotes) {
        this.ordernotes = ordernotes == null ? null : ordernotes.trim();
    }
}