package com.nf147.entity;

public class Path {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.PathID
     *
     * @mbg.generated
     */
    private String pathid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.PathName
     *
     * @mbg.generated
     */
    private String pathname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.OrderID
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.ProvinceID
     *
     * @mbg.generated
     */
    private String provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.PathPrice
     *
     * @mbg.generated
     */
    private Long pathprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.PathNotes
     *
     * @mbg.generated
     */
    private String pathnotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.PathID
     *
     * @return the value of path.PathID
     *
     * @mbg.generated
     */
    public String getPathid() {
        return pathid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.PathID
     *
     * @param pathid the value for path.PathID
     *
     * @mbg.generated
     */
    public void setPathid(String pathid) {
        this.pathid = pathid == null ? null : pathid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.PathName
     *
     * @return the value of path.PathName
     *
     * @mbg.generated
     */
    public String getPathname() {
        return pathname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.PathName
     *
     * @param pathname the value for path.PathName
     *
     * @mbg.generated
     */
    public void setPathname(String pathname) {
        this.pathname = pathname == null ? null : pathname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.OrderID
     *
     * @return the value of path.OrderID
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.OrderID
     *
     * @param orderid the value for path.OrderID
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.ProvinceID
     *
     * @return the value of path.ProvinceID
     *
     * @mbg.generated
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.ProvinceID
     *
     * @param provinceid the value for path.ProvinceID
     *
     * @mbg.generated
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.PathPrice
     *
     * @return the value of path.PathPrice
     *
     * @mbg.generated
     */
    public Long getPathprice() {
        return pathprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.PathPrice
     *
     * @param pathprice the value for path.PathPrice
     *
     * @mbg.generated
     */
    public void setPathprice(Long pathprice) {
        this.pathprice = pathprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.PathNotes
     *
     * @return the value of path.PathNotes
     *
     * @mbg.generated
     */
    public String getPathnotes() {
        return pathnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.PathNotes
     *
     * @param pathnotes the value for path.PathNotes
     *
     * @mbg.generated
     */
    public void setPathnotes(String pathnotes) {
        this.pathnotes = pathnotes == null ? null : pathnotes.trim();
    }
}