package com.nf147.entity;

public class Scope {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.ScopeID
     *
     * @mbg.generated
     */
    private String scopeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.ScopeName
     *
     * @mbg.generated
     */
    private String scopename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.ScopePrice
     *
     * @mbg.generated
     */
    private Long scopeprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.StationID
     *
     * @mbg.generated
     */
    private String stationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scope.ScopeNotes
     *
     * @mbg.generated
     */
    private String scopenotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.ScopeID
     *
     * @return the value of scope.ScopeID
     *
     * @mbg.generated
     */
    public String getScopeid() {
        return scopeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.ScopeID
     *
     * @param scopeid the value for scope.ScopeID
     *
     * @mbg.generated
     */
    public void setScopeid(String scopeid) {
        this.scopeid = scopeid == null ? null : scopeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.ScopeName
     *
     * @return the value of scope.ScopeName
     *
     * @mbg.generated
     */
    public String getScopename() {
        return scopename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.ScopeName
     *
     * @param scopename the value for scope.ScopeName
     *
     * @mbg.generated
     */
    public void setScopename(String scopename) {
        this.scopename = scopename == null ? null : scopename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.ScopePrice
     *
     * @return the value of scope.ScopePrice
     *
     * @mbg.generated
     */
    public Long getScopeprice() {
        return scopeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.ScopePrice
     *
     * @param scopeprice the value for scope.ScopePrice
     *
     * @mbg.generated
     */
    public void setScopeprice(Long scopeprice) {
        this.scopeprice = scopeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.StationID
     *
     * @return the value of scope.StationID
     *
     * @mbg.generated
     */
    public String getStationid() {
        return stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.StationID
     *
     * @param stationid the value for scope.StationID
     *
     * @mbg.generated
     */
    public void setStationid(String stationid) {
        this.stationid = stationid == null ? null : stationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scope.ScopeNotes
     *
     * @return the value of scope.ScopeNotes
     *
     * @mbg.generated
     */
    public String getScopenotes() {
        return scopenotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scope.ScopeNotes
     *
     * @param scopenotes the value for scope.ScopeNotes
     *
     * @mbg.generated
     */
    public void setScopenotes(String scopenotes) {
        this.scopenotes = scopenotes == null ? null : scopenotes.trim();
    }
}