package com.nf147.entity;

public class Station {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.StationID
     *
     * @mbg.generated
     */
    private String stationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.StationName
     *
     * @mbg.generated
     */
    private String stationname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.ProvinceID
     *
     * @mbg.generated
     */
    private String provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.CityID
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.AdminID
     *
     * @mbg.generated
     */
    private String adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.StationPhone
     *
     * @mbg.generated
     */
    private String stationphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.StationSite
     *
     * @mbg.generated
     */
    private String stationsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.StationNotes
     *
     * @mbg.generated
     */
    private String stationnotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.StationID
     *
     * @return the value of station.StationID
     *
     * @mbg.generated
     */
    public String getStationid() {
        return stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.StationID
     *
     * @param stationid the value for station.StationID
     *
     * @mbg.generated
     */
    public void setStationid(String stationid) {
        this.stationid = stationid == null ? null : stationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.StationName
     *
     * @return the value of station.StationName
     *
     * @mbg.generated
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.StationName
     *
     * @param stationname the value for station.StationName
     *
     * @mbg.generated
     */
    public void setStationname(String stationname) {
        this.stationname = stationname == null ? null : stationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.ProvinceID
     *
     * @return the value of station.ProvinceID
     *
     * @mbg.generated
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.ProvinceID
     *
     * @param provinceid the value for station.ProvinceID
     *
     * @mbg.generated
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.CityID
     *
     * @return the value of station.CityID
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.CityID
     *
     * @param cityid the value for station.CityID
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.AdminID
     *
     * @return the value of station.AdminID
     *
     * @mbg.generated
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.AdminID
     *
     * @param adminid the value for station.AdminID
     *
     * @mbg.generated
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.StationPhone
     *
     * @return the value of station.StationPhone
     *
     * @mbg.generated
     */
    public String getStationphone() {
        return stationphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.StationPhone
     *
     * @param stationphone the value for station.StationPhone
     *
     * @mbg.generated
     */
    public void setStationphone(String stationphone) {
        this.stationphone = stationphone == null ? null : stationphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.StationSite
     *
     * @return the value of station.StationSite
     *
     * @mbg.generated
     */
    public String getStationsite() {
        return stationsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.StationSite
     *
     * @param stationsite the value for station.StationSite
     *
     * @mbg.generated
     */
    public void setStationsite(String stationsite) {
        this.stationsite = stationsite == null ? null : stationsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.StationNotes
     *
     * @return the value of station.StationNotes
     *
     * @mbg.generated
     */
    public String getStationnotes() {
        return stationnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.StationNotes
     *
     * @param stationnotes the value for station.StationNotes
     *
     * @mbg.generated
     */
    public void setStationnotes(String stationnotes) {
        this.stationnotes = stationnotes == null ? null : stationnotes.trim();
    }
}