package com.nf147.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserID
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserNotes
     *
     * @mbg.generated
     */
    private String usernotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserID
     *
     * @return the value of user.UserID
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserID
     *
     * @param userid the value for user.UserID
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserName
     *
     * @return the value of user.UserName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserName
     *
     * @param username the value for user.UserName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserNotes
     *
     * @return the value of user.UserNotes
     *
     * @mbg.generated
     */
    public String getUsernotes() {
        return usernotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserNotes
     *
     * @param usernotes the value for user.UserNotes
     *
     * @mbg.generated
     */
    public void setUsernotes(String usernotes) {
        this.usernotes = usernotes == null ? null : usernotes.trim();
    }
}